### PR TITLE
Bug Fix: User Name

### LINKED ISSUE #40: FE / BE - User name is not persisting on Profile component re-render after altering/saving user data.
- [ ] determine what is required to 'resave' the user's name to database after user profile is edited…

### PR DESCRIPTION
**Pull request by rachael-t**
# PR Description
Please include a summary of the change:
- Edits code to fix the issue reported in #40 - a detailed explanation of the fix is provided in that issue.
- closes #40 

Commit Emojis:
:beetle: If it is a bug or issue fix, describe the issue that was fixed.

If it is a new feature, describe the feature and the iteration of the project spec it addresses.
- n/a bug fix

Note any questions or struggles as well.
- n/a

## Type of change
Please delete options that are not relevant.
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [X] My code follows the Turing style guidelines
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

File: code/web/src/modules/user/EditProfile.js [hunk 1]
```diff
@@ -28,7 +28,7 @@ class EditProfile extends Component {
     super(props)
     this.state = {
       user: {
-        name: this.props.user.name,
+        name: this.props.user.details.name,
```
Comment (atkinson-daniel) [inline code/web/src/modules/user/EditProfile.js:31]: Nice catch!

**Review by atkinson-daniel — APPROVED** [review]
